### PR TITLE
Checkout submodules recursively

### PR DESCRIPTION
**Pull request by neonichu**
We should checkout submodules recursively if the `submodule` option is `true`.

### CODE REVIEW

**Comment by kylef** [comment]
Makes sense, but maybe it would make sense to add `--recursive` to `clone_arguments` and do away with `init_submodules` entirely.

This is supported on git 1.6.5 and onwards

**Comment by segiddins** [comment]
:+1: with tests

**Comment by neonichu** [comment]
@kylef I think it is a good idea to not check out submodules by default, because they're probably dependencies and would just add time without any benefit

**Comment by kylef** [comment]
@neonichu They are not, and should not be by default. The recursive flag should only be added if `options[:submodules]`.

**Comment by neonichu** [comment]
@kylef ah OK, I misunderstood your comment - that sounds like a better implementation, will change

**Comment by segiddins** [comment]
OK, this should be ready to :ship:

**Pull request merged**
