### PR TITLE
Feature/use tar auto detection

### PR DESCRIPTION
**Pull request by akhomchenko**
Thank you for a great library!

### Description

Commit messages are more descriptive (I hope) but main idea is:

Sometimes files with extension (e.g. `bz2`) have different content (e.g. `gzip`). Given that most implementations (I haven't checked Solaris tar) support auto-detection for flat files, I think it is reasonable to use that.

What do you think?

### Testing

I have created 2 commits. First one: to showcase an issue. File was created with `tar czvf lib-actually-gzipped.tar.bz2 lib/`. It works fine with `bsdtar 2.8.3 - libarchive 2.8.3` that I have on my OSX but fails if I use `GNU tar 1.32`:

```
$ PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH" rake
```

### Notes

I'm not very familiar with Ruby.

P.S. Feel free to squash commits.

### CODE REVIEW

**Comment by gagoman** [comment]
Good day. Will someone have time to take a look and say yes / no to a feature? Thanks.

**Comment by akhomchenko** [comment]
Friendly ping. I am curious if you are interested in patch in general and something need to be fixed or you think it does not provide a lot of value. Thank you.

**Comment by endocrimes** [comment]
This should be safe - as much as I dislike it when extensions are wrong 😅

**Review by endocrimes — APPROVED** [review]
I'd give this a 👍  - but will ping folks for a second review

**Review by segiddins — APPROVED** [review]

**Comment by akhomchenko** [comment]
Good day. Thank you a lot for a quick review and approval! Do I need to do something to get it merged? I've checked both failures in Travis and I think they are not related to patch.

**Comment by endocrimes** [comment]
Yeah travis seems generally broken and this should be unrelated - we'll get this moved over to GitHub Actions soon ™️

**Pull request merged**
