### PR TITLE
Adds a to_s map during validation

### PR DESCRIPTION
**Pull request by orta**
Should handle CocoaPods passing in Pathnames instead of strings

### CODE REVIEW

**Review by dnkoutso — APPROVED** [review]

**Comment by dnkoutso** [comment]
Want to do it on 1-6 stable to ship 1.6.1?

**Comment by orta** [comment]
That branch doesn't exist yetfro mthe looks of it

**Comment by orta** [comment]
I made it based on current master

**Comment by dnkoutso** [comment]
Huh thats weird. Wonder if it did not get pushed. Ill check in a day

**Comment by dnkoutso** [comment]
This loads for me https://github.com/CocoaPods/cocoapods-downloader/tree/1-6-stable

**Pull request merged**
