### PR TITLE
Fix bug of Git shallow cloning is not used when branch is set #106

### PR DESCRIPTION
**Pull request by dimohamdy**
https://github.com/CocoaPods/cocoapods-downloader/issues/106

### CODE REVIEW

**Comment by dimohamdy** [comment]
@fabiopelosin Can you check this PR?

**Comment by dimohamdy** [comment]
@segiddins I will

**Comment by dimohamdy** [comment]
@segiddins I add a unit-test for it

**Comment by dimohamdy** [comment]
@segiddins Can you check the PR Please?

**Comment by dimohamdy** [comment]
@segiddins Any update or plan to merge this PR?

**Comment by dnkoutso** [comment]
@dimohamdy please rebase and squash into a single commit.

Add a changelog entry and make sure you rebased on latest master.

**Comment by dimohamdy** [comment]
@dnkoutso Please check the new PR https://github.com/CocoaPods/cocoapods-downloader/pull/117 and I will close this one

**Pull request closed without merging**
